[workspace]
members=[
    "tools/markdown",
    "tools/xdict",
    "tools/demo",
    "tools/string_art"
]


[workspace.dependencies]
thiserror = "1.0"
path-absolutize = "3.1.1"
markdown-it =  { version = "0.6", default-features = false }
regex       = ">= 1.0.0, < 2"
once_cell   = ">= 1.0.1, < 2"
