[package]
name = "string_art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
image = "0.25.0"
rayon = "1.10.0"
imageproc = "0.24.0"

